module.exports = [
  '1-Mgmt',
  '2-Production',
  '3-Guest',
  '31-Mgmt',
  '32-Production',
  '33-Guest',
  '34-Facilities',
  '35-IoT',
  '36-DC',
  '4-Facilities',
  '5-IoT',
  '6-DC',
  '61-Mgmt',
  '62-Production',
  '63-Guest',
  '64-Facilities',
  '65-IoT',
  '66-DC',
  'APAC',
  'AWS - Ohio',
  'AWS - Oregon',
  'AWS',
  'Azure',
  'Campus Sites',
  'Data Center & Other Areas',
  'Europe',
  'HQ San Francisco',
  'Lab-Kit',
  'London',
  'Main Hospital Site',
  'Medical Devices',
  'Nakatomi - In Scope',
  'Nakatomi Trading Corp.',
  'Operational Technology',
  'Out Of Scope',
  'Remote Offices',
  'Singapore',
  'United States',
  'VPN',
  'pcap',
];
