module.exports = [
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '7.8',
      vendor_specific_id: 'YSAR-22-0001',
      cvss_temporal_score: '0.0',
      title:
        'Inappropriate access privilege vulnerability in Yokogawa CENTUM and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-083-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2022-22141',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-22141',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.8',
      vendor_specific_id: 'YSAR-15-0003',
      cvss_temporal_score: '0.0',
      title:
        'Stack-Based Buffer Overflow in the communication functions in CENTUM and other Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-15-253-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2015-5626',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2015-5626',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.8',
      vendor_specific_id: 'YSAR-15-0003',
      cvss_temporal_score: '0.0',
      title:
        'Stack-Based Buffer Overflow in the communication functions in CENTUM and other Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-15-253-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2015-5627',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2015-5627',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.8',
      vendor_specific_id: 'YSAR-15-0003',
      cvss_temporal_score: '0.0',
      title:
        'Stack-Based Buffer Overflow in the communication functions in CENTUM and other Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-15-253-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2015-5628',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2015-5628',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '7.5',
      vendor_specific_id: 'YSAR-14-0003E',
      cvss_temporal_score: '5.6',
      title:
        'Arbitrary File Read/Write Vulnerability in CENTUM series and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'LOW',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'NONE',
      icsa_id: 'ICSA-14-260-01A',
      cvss_confidentiality_impact: 'PARTIAL',
      cve_id: 'CVE-2014-5208',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'PARTIAL',
      id: 'CVE-2014-5208',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'PARTIAL',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.3',
      vendor_specific_id: 'YSAR-14-0002E',
      cvss_temporal_score: '6.9',
      title: 'Buffer Overflow Vulnerability in CENTUM systems and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'MEDIUM',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'NONE',
      icsa_id: 'ICSA-14-189-01',
      cvss_confidentiality_impact: 'PARTIAL',
      cve_id: 'CVE-2014-3888',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2014-3888',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'PARTIAL',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.1',
      vendor_specific_id: 'YSAR-22-0001',
      cvss_temporal_score: '0.0',
      title:
        'Malformed packet handling vulnerability in Yokogawa CENTUM and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-083-01',
      cvss_confidentiality_impact: 'NONE',
      cve_id: 'CVE-2022-21177',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-21177',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.3',
      vendor_specific_id: 'YSAR-14-0001E',
      cvss_temporal_score: '0.0',
      title: 'Heap-based buffer overflow in BKCLogSvr.exe in Yokogawa CENTUM',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'MEDIUM',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'NONE',
      icsa_id: 'ICSA-14-070-01A',
      cvss_confidentiality_impact: 'COMPLETE',
      cve_id: 'CVE-2014-0781',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2014-0781',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'COMPLETE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '7.8',
      vendor_specific_id: 'YSAR-19-0003',
      cvss_temporal_score: '0.0',
      title: 'Unquoted Service Path vulnerability in Yokogawa Products',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-19-274-02',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2019-6008',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2019-6008',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '10.0',
      vendor_specific_id: 'YSAR-22-0003',
      cvss_temporal_score: '0.0',
      title: 'Log4J vulnerability in Yokogawa CENTUM VP',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: '',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2021-44228 (YOKOGAWA)',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2021-44228 (YOKOGAWA)',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '7.5',
      vendor_specific_id: 'YSAR-18-008',
      cvss_temporal_score: '0.0',
      title:
        'Denial of Service (DoS) vulnerability in Vnet/IP Open Communication Driver',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-19-003-02',
      cvss_confidentiality_impact: 'NONE',
      cve_id: 'CVE-2018-16196',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2018-16196',
      suppressed: 'false',
      cvss_integrity_impact: 'NONE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '6.4',
      vendor_specific_id: 'YSAR-22-0006',
      cvss_temporal_score: '0.0',
      title:
        'Data breach / falsification and resource exhaustion vulnerability in Yokogawa CAMS for HIS',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-174-02',
      cvss_confidentiality_impact: 'LOW',
      cve_id: 'CVE-2022-30707',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-30707',
      suppressed: 'false',
      cvss_integrity_impact: 'LOW',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '7.5',
      vendor_specific_id: 'YSAR-22-0004',
      cvss_temporal_score: '0.0',
      title: 'NULL pointer dereference vulnerability in Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-123-01',
      cvss_confidentiality_impact: 'NONE',
      cve_id: 'CVE-2019-0203',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2019-0203',
      suppressed: 'false',
      cvss_integrity_impact: 'NONE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '7.8',
      vendor_specific_id: 'YSAR-22-0001',
      cvss_temporal_score: '0.0',
      title: 'Command injection vulnerability in Yokogawa CENTUM and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-083-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2022-22148',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-22148',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.1',
      vendor_specific_id: 'YSAR-22-0001',
      cvss_temporal_score: '0.0',
      title:
        'Malformed packet handling vulnerability in Yokogawa CENTUM and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-083-01',
      cvss_confidentiality_impact: 'NONE',
      cve_id: 'CVE-2022-22145',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-22145',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.3',
      vendor_specific_id: 'YSAR-21-0001',
      cvss_temporal_score: '0.0',
      title: 'Buffer overflow vulnerability in VB6 in Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'MEDIUM',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'NONE',
      icsa_id: '',
      cvss_confidentiality_impact: 'COMPLETE',
      cve_id: 'CVE-2008-4255',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2008-4255',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'COMPLETE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.3',
      vendor_specific_id: 'YSAR-14-0001E',
      cvss_temporal_score: '0.0',
      title:
        'Stack-based buffer overflow in BKESimmgr.exe in the Expanded Test Functions package in Yokogawa CENTUM',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'MEDIUM',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'NONE',
      icsa_id: 'ICSA-14-070-01A',
      cvss_confidentiality_impact: 'PARTIAL',
      cve_id: 'CVE-2014-0782',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2014-0782',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'PARTIAL',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.8',
      vendor_specific_id: 'YSAR-20-0001',
      cvss_temporal_score: '0.0',
      title: 'Improper authentication vulnerability in Yokogawa CENTUM',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-20-224-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2020-5608',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2020-5608',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.3',
      vendor_specific_id: 'YSAR-21-0001',
      cvss_temporal_score: '0.0',
      title: 'Buffer overflow vulnerability in VB6 in Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'MEDIUM',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'NONE',
      icsa_id: '',
      cvss_confidentiality_impact: 'COMPLETE',
      cve_id: 'CVE-2008-3704',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2008-3704',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'COMPLETE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.3',
      vendor_specific_id: 'YSAR-14-0001E',
      cvss_temporal_score: '0.0',
      title: 'Stack-based buffer overflow in BKBCopyD.exe in Yokogawa CENTUM',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'MEDIUM',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'NONE',
      icsa_id: 'ICSA-14-070-01A',
      cvss_confidentiality_impact: 'PARTIAL',
      cve_id: 'CVE-2014-0784',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2014-0784',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'PARTIAL',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.8',
      vendor_specific_id: 'YSAR-22-0001',
      cvss_temporal_score: '0.0',
      title: 'Hard-coded password vulnerability in Yokogawa CENTUM and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-083-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2022-21194',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-21194',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.8',
      vendor_specific_id: 'YSAR-22-0001',
      cvss_temporal_score: '0.0',
      title:
        'Assured immutable data vulnerability in Yokogawa CENTUM and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-083-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2022-21808',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-21808',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.5',
      vendor_specific_id: 'YSAR-21-0001',
      cvss_temporal_score: '0.0',
      title: 'Numeric error vulnerability in VB6 in Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'MEDIUM',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'SINGLE',
      icsa_id: '',
      cvss_confidentiality_impact: 'COMPLETE',
      cve_id: 'CVE-2008-4254',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2008-4254',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'COMPLETE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.0',
      vendor_specific_id: 'YSAR-22-0003',
      cvss_temporal_score: '0.0',
      title: 'Log4J vulnerability in Yokogawa CENTUM VP',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: '',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2021-45046 (YOKOGAWA)',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2021-45046 (YOKOGAWA)',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.8',
      vendor_specific_id: 'YSAR-22-0001',
      cvss_temporal_score: '0.0',
      title:
        'Assured immutable data vulnerability in Yokogawa CENTUM and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-083-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2022-22729',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-22729',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.3',
      vendor_specific_id: 'YSAR-19-0002',
      cvss_temporal_score: '0.0',
      title: 'Vulnerability of Microsoft CAPICOM in Yokogawa Products',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'MEDIUM',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'NONE',
      icsa_id: '',
      cvss_confidentiality_impact: 'COMPLETE',
      cve_id: 'CVE-2007-0940',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2007-0940',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'COMPLETE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '6.5',
      vendor_specific_id: 'YSAR-22-0004',
      cvss_temporal_score: '0.0',
      title: 'Improper input validation vulnerability in Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-123-01',
      cvss_confidentiality_impact: 'NONE',
      cve_id: 'CVE-2018-11782',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2018-11782',
      suppressed: 'false',
      cvss_integrity_impact: 'NONE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.1',
      vendor_specific_id: 'YSAR-22-0001',
      cvss_temporal_score: '0.0',
      title:
        'Malformed packet handling vulnerability in Yokogawa CENTUM and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-083-01',
      cvss_confidentiality_impact: 'NONE',
      cve_id: 'CVE-2022-22151',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-22151',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '7.8',
      vendor_specific_id: 'YSAR-22-0004',
      cvss_temporal_score: '0.0',
      title: 'OS command injection vulnerability in Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-123-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2022-27188',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-27188',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.8',
      vendor_specific_id: 'YSAR-19-0001',
      cvss_temporal_score: '0.0',
      title:
        'Vulnerability of access control in License Manager Service of Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-19-029-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2019-5909',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2019-5909',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '7.8',
      vendor_specific_id: 'YSAR-22-0001',
      cvss_temporal_score: '0.0',
      title:
        'Uncontrolled search path vulnerability in Yokogawa CENTUM and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-083-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2022-23401',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-23401',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.8',
      vendor_specific_id: 'YSAR-20-0001',
      cvss_temporal_score: '0.0',
      title: 'Path traversal vulnerability in Yokogawa CENTUM',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-20-224-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2020-5609',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2020-5609',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.5',
      vendor_specific_id: 'YSAR-21-0001',
      cvss_temporal_score: '0.0',
      title:
        'Permissions, privilege and access control vulnerability in VB6 in Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'MEDIUM',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'SINGLE',
      icsa_id: '',
      cvss_confidentiality_impact: 'COMPLETE',
      cve_id: 'CVE-2008-4252',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2008-4252',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'COMPLETE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.5',
      vendor_specific_id: 'YSAR-21-0001',
      cvss_temporal_score: '0.0',
      title:
        'Resource management error vulnerability in VB6 in Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'MEDIUM',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'SINGLE',
      icsa_id: '',
      cvss_confidentiality_impact: 'COMPLETE',
      cve_id: 'CVE-2008-4253',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2008-4253',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'COMPLETE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '8.5',
      vendor_specific_id: 'YSAR-21-0001',
      cvss_temporal_score: '0.0',
      title:
        'Resource management error vulnerability in VB6 in Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'MEDIUM',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'SINGLE',
      icsa_id: '',
      cvss_confidentiality_impact: 'COMPLETE',
      cve_id: 'CVE-2008-4256',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2008-4256',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'COMPLETE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.8',
      vendor_specific_id: 'YSAR-22-0001',
      cvss_temporal_score: '0.0',
      title: 'Hard-coded password vulnerability in Yokogawa CENTUM and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-083-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2022-23402',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2022-23402',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '6.5',
      vendor_specific_id: 'YSAR-18-0001',
      cvss_temporal_score: '0.0',
      title: 'Faked and blocked alarms Vulnerability in CENTUM and Exaopc',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-18-102-01',
      cvss_confidentiality_impact: 'LOW',
      cve_id: 'CVE-2018-8838',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'HIGH',
      id: 'CVE-2018-8838',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.0',
      vendor_specific_id: 'YSAR-14-0001E',
      cvss_temporal_score: '0.0',
      title: 'Stack-based buffer overflow in BKHOdeq.exe in Yokogawa CENTUM',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'LOW',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'NONE',
      icsa_id: 'ICSA-14-070-01A',
      cvss_confidentiality_impact: 'PARTIAL',
      cve_id: 'CVE-2014-0783',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'COMPLETE',
      id: 'CVE-2014-0783',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'PARTIAL',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '5.0',
      vendor_specific_id: 'YSAR-22-0004',
      cvss_temporal_score: '0.0',
      title: 'Resource management vulnerability in Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_access_complexity: 'LOW',
      cvss_exploitability: 'UNDEFINED',
      cvss_remediation_level: 'OFFICIAL_FIX',
      cvss_authentication: 'NONE',
      icsa_id: 'ICSA-22-123-01',
      cvss_confidentiality_impact: 'NONE',
      cve_id: 'CVE-2015-0248',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'PARTIAL',
      id: 'CVE-2015-0248',
      suppressed: 'false',
      cvss_access_vector: 'NETWORK',
      cvss_integrity_impact: 'NONE',
    },
  },
  {
    timestamp: 1723595945,
    value: {
      cvss_score: '9.1',
      vendor_specific_id: 'YSAR-22-0004',
      cvss_temporal_score: '0.0',
      title: 'Improper authentication vulnerability in Yokogawa products',
      matching_confidence: 'maybeProduct',
      cvss_remediation_level: 'OFFICIAL_FIX',
      icsa_id: 'ICSA-22-123-01',
      cvss_confidentiality_impact: 'HIGH',
      cve_id: 'CVE-2022-26034',
      cvss_reporting_confidence: 'CONFIRMED',
      cvss_availability_impact: 'NONE',
      id: 'CVE-2022-26034',
      suppressed: 'false',
      cvss_integrity_impact: 'HIGH',
    },
  },
];
